import { database } from './neon-db';

export type PortfolioProject = {
 id:string; title:string; slug:string; category:string; status:'current'|'completed'|'in_progress'; summary:string; body:string; projectUrl:string; coverMediaId:string; galleryMediaIds:string[]; published:boolean; sortOrder:number;
};
function map(row:any):PortfolioProject {return {id:row.id,title:row.title,slug:row.slug,category:row.category,status:row.status,summary:row.summary,body:row.body,projectUrl:row.project_url,coverMediaId:row.cover_media_id,galleryMediaIds:row.gallery_media_ids||[],published:row.published,sortOrder:row.sort_order};}
export async function listProjects(includeDrafts=false):Promise<PortfolioProject[]>{const sql=database();const rows=includeDrafts?await sql`SELECT * FROM portfolio_projects ORDER BY sort_order,created_at`:await sql`SELECT * FROM portfolio_projects WHERE published=true ORDER BY sort_order,created_at`;return rows.map(map);}
export async function saveProject(input:PortfolioProject):Promise<PortfolioProject>{const sql=database();const rows=await sql`INSERT INTO portfolio_projects (id,title,slug,category,status,summary,body,project_url,cover_media_id,gallery_media_ids,published,sort_order,updated_at) VALUES (${input.id},${input.title},${input.slug},${input.category},${input.status},${input.summary},${input.body},${input.projectUrl},${input.coverMediaId},${JSON.stringify(input.galleryMediaIds)}::jsonb,${input.published},${input.sortOrder},now()) ON CONFLICT (id) DO UPDATE SET title=excluded.title,slug=excluded.slug,category=excluded.category,status=excluded.status,summary=excluded.summary,body=excluded.body,project_url=excluded.project_url,cover_media_id=excluded.cover_media_id,gallery_media_ids=excluded.gallery_media_ids,published=excluded.published,sort_order=excluded.sort_order,updated_at=now() RETURNING *`;return map(rows[0]);}
export async function deleteProject(id:string){const sql=database();await sql`DELETE FROM portfolio_projects WHERE id=${id}`;}
