'use client';
import { useEffect,useMemo,useRef,useState } from 'react';
import type { PortfolioProject } from '@/lib/portfolio';
import { defaultSite, type Section, type SiteConfig } from '@/lib/default-site';
import PortfolioSection from '@/components/PortfolioSection';
function image(site:SiteConfig,id:string){return site.media.find(m=>m.id===id)}
function Text({value}:{value:string}){return <>{value.split('\n').map((s,i)=><span key={i}>{i>0&&<br/>}{s}</span>)}</>}
function Content({section,site,index}:{section:Section;site:SiteConfig;index:number}){
 const media=section.mediaIds.map(id=>image(site,id)).filter(Boolean);
 if(section.type==='services')return <section className="services-panel wrap" id={section.id}><div className="service-tabs"><span className="tab-active">{section.title}</span><span>Strategy</span><span>Design</span><span>Development</span><span>Automation</span></div><div className="services-grid">{section.items.map((x,i)=><article className="service-card" key={i}><span>{String(i+1).padStart(2,'0')} / {x.title.toUpperCase()}</span><h3>{x.title}</h3><p>{x.body}</p><span className="service-arrow" aria-hidden="true">↗</span></article>)}</div></section>;
 if(section.type==='media'||section.type==='gallery')return <section id={section.id} className="media-section wrap"><div className="section-meta"><span>{section.label}</span></div><div className="media-heading"><h2><Text value={section.title}/></h2><p>{section.body}</p></div><div className={'media-grid '+(section.type==='gallery'?'gallery-grid':'')}>{media.map(m=><figure key={m!.id}>{m!.kind==='video'?<video controls playsInline preload="metadata" src={m!.url}/>:<img src={m!.url} alt={m!.filename} loading="lazy"/>}</figure>)}</div></section>;
 return <section className={index%2===0?'about-band':'editorial wrap'} id={section.id}>{index%2===0?<div className="wrap about-grid"><div><span className="section-label">{section.label}</span><h2><Text value={section.title}/></h2></div><div><p>{section.body}</p><div className="about-rule"><span>ROOTED IN PALAWAN</span><span>WORKING EVERYWHERE</span></div></div></div>:<><div className="section-meta"><span>{section.label}</span><span>MADE FOR REAL BUSINESS</span></div><div className="editorial-grid"><h2><Text value={section.title}/></h2><div><p>{section.body}</p><a href="#contact" className="text-link">LET'S BUILD SOMETHING <span aria-hidden="true">↗</span></a></div></div></>}</section>;
}
export default function Home(){const [site,setSite]=useState<SiteConfig>(defaultSite),[projects,setProjects]=useState<PortfolioProject[]>([]),[menu,setMenu]=useState(false),clicks=useRef<number[]>([]);useEffect(()=>{fetch('/api/site').then(r=>r.ok?r.json() as Promise<SiteConfig>:null).then(s=>s&&setSite(s)).catch(()=>{});fetch('/api/portfolio').then(r=>r.ok?r.json() as Promise<{projects:PortfolioProject[]}>:null).then(d=>d?.projects&&setProjects(d.projects)).catch(()=>{});},[]);const hero=image(site,site.heroMediaId),logo=image(site,site.logoId);const style=useMemo(()=>({ '--navy':site.palette.navy,'--blue':site.palette.blue,'--ink':site.palette.ink,'--paper':site.palette.paper,'--white':site.palette.white,'--muted':site.palette.muted,'--heading-font':`'${site.fonts.heading}'`,'--body-font':`'${site.fonts.body}'` } as React.CSSProperties),[site]);function logoClick(e:React.MouseEvent){clicks.current=[...clicks.current.filter(t=>Date.now()-t<1200),Date.now()];if(clicks.current.length>=3){e.preventDefault();window.location.href='/admin';}}
return <div className="page-shell" style={style}>
<header className="header wrap" id="top"><a className={"brand"+(logo?" has-logo":"")+(logo&&["71a68b76-0b86-439c-9617-c711fbfc85f5","b4dacb8f-1bda-469a-84a9-c683b4d048d5"].includes(logo.id)?" uncropped-logo":"")} href="#top" onClick={logoClick} aria-label={`${site.name} home`}><span className="brand-mark">{logo?<img src={logo.url} alt=""/>:<>m<span>.</span></>}</span><span className="brand-text"><strong>{site.name}</strong><small>{site.descriptor}</small></span></a><nav className="desktop-nav" aria-label="Main navigation">{site.nav.map((n,i)=><a href={'#'+n.sectionId} key={i}>{n.label}</a>)}{!site.nav.some(n=>n.sectionId==='projects')&&<a href="#projects">Projects</a>}</nav><div className="header-end"><span className="location">{site.location}</span><a className="header-cta" href="#contact">LET'S TALK <span aria-hidden="true">↗</span></a><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} aria-controls="mobile-nav"><span/><span/></button></div></header>
{menu&&<nav className="mobile-nav" id="mobile-nav" aria-label="Mobile navigation">{site.nav.map((n,i)=><a href={'#'+n.sectionId} key={i} onClick={()=>setMenu(false)}>{n.label}</a>)}{!site.nav.some(n=>n.sectionId==='projects')&&<a href="#projects" onClick={()=>setMenu(false)}>Projects</a>}</nav>}
<main><section className="hero" aria-labelledby="hero-title"><div className="hero-photo" style={{backgroundImage:hero?.kind==='image'?`url('${hero.url}')`:!hero?`url('${site.heroImage}')`:undefined}}/>{hero?.kind==='video'&&<video className="hero-video" src={hero.url} autoPlay muted playsInline loop/>}<div className="hero-tint"/><div className="hero-inner wrap"><div className="hero-copy"><p className="eyebrow">{site.eyebrow}</p><h1 id="hero-title"><Text value={site.headline}/></h1><p className="hero-intro">{site.intro}</p><div className="hero-actions"><a className="button-primary" href={'#'+(site.sections.find(s=>s.visible)?.id||'contact')}>{site.heroButton} <span aria-hidden="true">↗</span></a><a className="button-line" href="#contact">START A CONVERSATION <span aria-hidden="true">↗</span></a></div></div><div className="hero-side"><span className="side-line"/><span>IDEAS, DESIGN<br/>& TECHNOLOGY<br/>IN MOTION</span></div><div className="hero-index"><span className="index-big">01<span>/03</span></span><p>Independent thinking.<br/>Built for what’s next.</p><div className="index-dots"><span className="active"/><span/><span/></div></div></div><div className="hero-bottom wrap"><span>SCROLL TO EXPLORE</span><span className="scroll-line"/><span>01 — 04</span></div></section>
{site.sections.filter(s=>s.visible).map((s,i)=><Content section={s} site={site} index={i} key={s.id}/>)}
<PortfolioSection site={site} projects={projects}/>
<section className="contact wrap" id="contact"><p className="section-label">LET'S TALK</p><div className="contact-grid"><h2>Have something<br/><em>in mind?</em></h2><div><p>Tell us what you're building. We’ll start with a conversation.</p><a className="contact-button" href={`mailto:${site.email}`}>GET IN TOUCH <span aria-hidden="true">↗</span></a></div></div></section></main>
<footer className="footer footer-new"><div className="wrap"><div className="footer-main"><div><div className="footer-kicker">{site.descriptor}</div><h2>{site.footer.headline}</h2><p>{site.footer.description}</p></div><a href={`mailto:${site.email}`} className="footer-mail">{site.email} <span aria-hidden="true">↗</span></a></div><div className="footer-bottom"><a href="#top" className="footer-wordmark">{site.name}</a><nav aria-label="Footer navigation">{site.footer.links.map((l,i)=><a key={i} href={l.url}>{l.label}</a>)}</nav><span>{site.footer.copyright}</span></div></div></footer>
</div>}
